### ISSUE TITLE
pip install / python setup.py error: Multiple top-level modules discovered in a flat-layout: ['run', 'install_cli'].

### ISSUE THREAD

**Issue by idcrook** [wakatime/wakatime-cli-pip#1]
```
pip3 install --user wakatime
Collecting wakatime
  Using cached wakatime-14.0.0.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level modules discovered in a flat-layout: ['run', 'install_cli'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple modules
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

other variations showed same error, e.g.

`pip3 install --user https://github.com/wakatime/wakatime-cli-pip/archive/refs/heads/main.zip`

Did a git clone of this repo and got the error as well

```
python3 setup.py install --user
error: Multiple top-level modules discovered in a flat-layout: ['run', 'install_cli'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple modules
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

I figured out a **fix/workaround**: changed name of `run.py` to `run` (dropping the `.py` extension) in my local clone and things worked

```shell
$ mv run.py run
$ python3 setup.py install --user
running install
/usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating wakatime.egg-info
writing wakatime.egg-info/PKG-INFO
writing dependency_links to wakatime.egg-info/dependency_links.txt
writing entry points to wakatime.egg-info/entry_points.txt
writing top-level names to wakatime.egg-info/top_level.txt
writing manifest file 'wakatime.egg-info/SOURCES.txt'
reading manifest file 'wakatime.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'run.py'
adding license file 'LICENSE'
writing manifest file 'wakatime.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying install_cli.py -> build/lib
creating build/bdist.macosx-10.13-x86_64
creating build/bdist.macosx-10.13-x86_64/egg
copying build/lib/install_cli.py -> build/bdist.macosx-10.13-x86_64/egg
byte-compiling build/bdist.macosx-10.13-x86_64/egg/install_cli.py to install_cli.cpython-311.pyc
creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying wakatime.egg-info/PKG-INFO -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying wakatime.egg-info/SOURCES.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying wakatime.egg-info/dependency_links.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying wakatime.egg-info/entry_points.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying wakatime.egg-info/not-zip-safe -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying wakatime.egg-info/top_level.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
creating dist
creating 'dist/wakatime-14.0.0-py3.11.egg' and adding 'build/bdist.macosx-10.13-x86_64/egg' to it
removing 'build/bdist.macosx-10.13-x86_64/egg' (and everything under it)
Processing wakatime-14.0.0-py3.11.egg
creating /Users/dpc/Library/Python/3.11/lib/python/site-packages/wakatime-14.0.0-py3.11.egg
Extracting wakatime-14.0.0-py3.11.egg to /Users/dpc/Library/Python/3.11/lib/python/site-packages
Adding wakatime 14.0.0 to easy-install.pth file
Installing wakatime script to /Users/dpc/Library/Python/3.11/bin

Installed /Users/dpc/Library/Python/3.11/lib/python/site-packages/wakatime-14.0.0-py3.11.egg
Processing dependencies for wakatime==14.0.0
Finished processing dependencies for wakatime==14.0.0
```

**Comment by idcrook** [comment]
spoke too soon.  trying to run the script named `wakatime` that gets placed in path, it yields an error

```
#!/usr/local/opt/python@3.11/bin/python3.11
# EASY-INSTALL-ENTRY-SCRIPT: 'wakatime==14.0.0','console_scripts','wakatime'
import re
import sys

Traceback (most recent call last):
  File "/Users/dpc/Library/Python/3.11/bin/wakatime", line 33, in <module>
    sys.exit(load_entry_point('wakatime==14.0.0', 'console_scripts', 'wakatime')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpc/Library/Python/3.11/bin/wakatime", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'run'
```

**Comment by idcrook** [comment]
the main issue is the error in `pip`/setup.py prevents the `install_cli.py` code from being run

**Comment by idcrook** [comment]
```shell
$ pip3 -V
pip 23.0.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
```

**Comment by idcrook** [comment]
found a finish to the "Workaround" above that sticks

```
cp run /Users/dpc/Library/Python/3.11/lib/python/site-packages/run.py
```

now running `wakatime` works

```
$ which wakatime
/Users/dpc/Library/Python/3.11/bin/wakatime
$ wakatime
Command line interface used by all WakaTime text editor plugins.

Usage:
  wakatime-cli [flags]

<<< snip >>>
```

So this is probably solved with an update to the MANIFEST and setup.py configuration.

**Comment by alanhamlett** [comment]
Can you try with v14.0.1?

**Comment by idcrook** [comment]
Seems to be working. no errors during install, and wrapper works too

```shell
❯ pip install --user wakatime
Collecting wakatime
  Downloading wakatime-14.0.1.tar.gz (7.0 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wakatime
  Building wheel for wakatime (setup.py) ... done
  Created wheel for wakatime: filename=wakatime-14.0.1-py3-none-any.whl size=7048 sha256=1264ebbfb9e5a08b5018222332d2b276877c7d35e94146ee2946214b82462341
  Stored in directory: /Users/dpc/Library/Caches/pip/wheels/d7/55/ba/663b58726ccb92cbf0c2abc6d8e1939257d6b8f91d46eeee6e
Successfully built wakatime
Installing collected packages: wakatime
Successfully installed wakatime-14.0.1
❯ which wakatime
/Users/dpc/Library/Python/3.11/bin/wakatime
❯ wakatime
Command line interface used by all WakaTime text editor plugins.

Usage:
  wakatime-cli [flags]
```

**Comment by idcrook** [comment]
Will CLOSE as it is FIXED

v14.0.1 <https://github.com/wakatime/wakatime-cli-pip/commit/e01137af809e6daf364aaae4a58447189f694a09>
